Revert "usb: roles: set switch registered flag early on"
../drivers/usb/roles/class.c:339:6: error: no member named 'registered' in 'struct usb_role_switch'
  339 |         sw->registered = true;
      |         ~~  ^
../drivers/usb/roles/class.c:343:7: error: no member named 'registered' in 'struct usb_role_switch'
  343 |                 sw->registered = false;
      |                 ~~  ^

This reverts commit a883b652951c2abd51ef0d71f44402e51664e37c.